hepsi: derle calistir
derle:
	g++ -I ./include -o ./lib/Liste.o -c ./src/Liste.cpp
	g++ -I ./include -o ./lib/Sayi.o -c ./src/Sayi.cpp
	g++ -I ./include -o ./bin/main ./lib/Sayi.o ./src/main.cpp
calistir:
	./bin/main